apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
    - name: http
      port: 8080          # Service port (inside cluster)
      targetPort: 8080    # Container port
      nodePort: 30080     # Host-accessible port (30000–32767)
