apiVersion: v1
kind: Service
metadata:
  name: ws-service
spec:
  type: NodePort
  selector:
    app: ws-service
  ports:
    - name: http
      port: 8888          # Service port (inside cluster)
      targetPort: 8888    # Container port
      nodePort: 30082     # Host-accessible port (30000–32767)
